### ISSUE TITLE
Having obfuscate_id in more than one model causes a error.

### ISSUE THREAD

**Issue by Gerhardk** [namick/obfuscate_id#21]
Environment: 
I am running Ruby 1.9.3, Rails 3.2.15 and postgres db

I have to separate models, with different obfuscate_id spin: 
```ruby
class Promotion < ActiveRecord::Base
   obfuscate_id spin: 33549763
end

class Survey < ActiveRecord::Base
  obfuscate_id spin: 73549763
end
```

I am getting the following error when I have obfuscate_id spin: 12345678 in two or more models: 
```ruby
ActiveRecord::StatementInvalid: PG::Error: ERROR:  value "8867469274" is out of range for type integer
: SELECT  "table_name".* FROM "table_name"  WHERE "table_name"."id" = $1 LIMIT 1
```
This only happens on the update of the model.

**Comment by ACPK** [comment]
+1. I'm also getting this issue: Couldn't find Recommendation with an out of range value for 'id'.

I'm trying to use the latest fork:  gem "obfuscate_id", github: 'ziyadbasheer/obfuscate_id'

**Comment by namick** [comment]
This is fixed now.  I just added tests to show two models (Post and Comment) each using obfuscate_id and having different spins.

https://github.com/namick/obfuscate_id/blob/master/spec/integration/post_with_comment_spec.rb#L47-L83

Please reopen this issue if you are still having problems.

**Comment by suupic** [comment]
ActiveRecord::RecordNotFound: Couldn't find User with an out of range value for 'id'

in rails 4.2.0

**Comment by DannyBen** [comment]
I am also getting the same error as @suupic 
`RecordNotFound: Couldn't find Site with an out of range ID`

It is not directly related to the original topic - since I only have it in one model, but I figured maybe it is not desired to have more and more issues talking about a similar problem.

I have tried this in two different models in my application, just to be certain.
